### ISSUE TITLE
Failed to load the regex-railroad-diagram-fork package

### ISSUE THREAD

**Issue by ccpwcn** [mikesprague/atom-regex-railroad-diagrams-fork#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [regex-railroad-diagram-fork](https://github.com/mikesprague/atom-regex-railroad-diagrams-fork) package 0.17.5

### Stack Trace

Failed to load the regex-railroad-diagram-fork package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'regex-railroad-diagram'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'regex-railroad-diagram'. A type with that name is already registered.
    at Error (native)
    at /packages/regex-railroad-diagram/lib/railroad-diagram-element.coffee:60:52)
    at /packages/regex-railroad-diagram/lib/railroad-diagram-element.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/regex-railroad-diagram-fork/lib/regex-railroad-diagram.coffee:4:26)
    at /packages/regex-railroad-diagram-fork/lib/regex-railroad-diagram.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -4:18.7.0 application:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:14.6.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:56.5.0 activate-power-mode:toggle (input.hidden-input)
     -3:52.4.0 core:move-up (input.hidden-input)
     -3:52.2.0 core:move-down (input.hidden-input)
  2x -3:51.8.0 core:move-up (input.hidden-input)
     -3:48 command-palette:toggle (input.hidden-input)
     -3:43.4.0 core:move-down (input.hidden-input)
     -3:43 core:confirm (input.hidden-input)
     -3:43 settings-view:install-packages-and-themes (input.hidden-input)
     -3:40.8.0 core:confirm (input.hidden-input)
     -2:57.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:30.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.8.0 core:confirm (input.hidden-input)
     -1:21.8.0 settings-view:install-packages-and-themes (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:20.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-beautify 0.29.22 
language-groovy 0.6.0 
language-lua 0.9.11 
markdown-writer 2.6.4 
regex-railroad-diagram-fork 0.17.5 
script 3.14.1 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by mikesprague** [comment]
That's an indication that you have the original installed still. You can fix that by uninstalling the original package (regex-railroad-diagram without the "-fork").
